# default type

apiVersion: v1
kind: secret
metadata:
  name: nabula-prod-secret
  namespace: nebula-prod-namespace
type: opaque
stringData:
  username: Dami
  password: Admin@1234
  api-token: jdfvhj3fbv
  
# dockerconfigjason

type: Kubernetes.io/dockerconfigjason
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "myregistry.example.com": {
          "username": "user123",
          "password": "p@ssw0rd!",
          "email": "dev@example.com",
          "auth": "dXNlcjEyMzpwQHNzdzByZCE="
        }
      }
    }

# basic auth

type: Kubernetes.io/basic-auth
stringData:
  user: goldy
  password: admin123

# ssh auth

type: kubernetes.io/ssh-auth
stringData:
  ssh-private-key: ....kcd....

# tls

type: Kubernetes.io/tls
stringData:
  tls.cert:
  tls.key:    